#!/usr/bin/python  

import sys
import os
emojis_list = '/usr/local/bin/emojis_list'
emojis = []
with open(emojis_list, 'r') as f:
    emojis = f.readlines()

def get_emoji_from_str(s):
    for emoji in emojis:
        if (s in emoji) or (emoji in s):
            return emoji.strip('\n')

if __name__ == "__main__":
    if len(sys.argv) <= 1:
        print("usage: get_emoji 'smile'")
        sys.exit(1)
    emoji = get_emoji_from_str(str(sys.argv[1]))
    print (emoji)
